### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by fela98** [werk85/fetch-intercept#10]
Are there any TypeScript definitions available anywhere for this module? Would really appreciate to be able to use this in my TypeScript environment.

Keep up the good work! 👍

**Comment by mlegenhausen** [comment]
Currently not but feel free to contribute.

**Comment by luchopcerra** [comment]
+1

**Comment by Xceno** [comment]
Here are some quick custom typings. They probably need some love though.
```
declare module "fetch-intercept" {
    export interface FetchInterceptor
    {
        request(url: string, config: any): any[];
        requestError(error: any): Promise<any>;
        response(response: Response): Response;
        responseError(error: any): Promise<any>;
    }

    export function register(interceptor: FetchInterceptor): () => void;
    export function clear(): void;
}
```

**Comment by sjmcdowall** [comment]
@xceno how about submitting that to @types ??  Assuming (since it's been Feb) that @mlegenhausen isn't going to add this to this repo?

**Comment by Xceno** [comment]
@sjmcdowall Sorry, didn't watch my Github notifications. Thanks for making the PR! 🥇
Glad it's useful for you guys :)

**Comment by sjmcdowall** [comment]
@mlegenhausen -- So I submitted the PR 3 days ... any movement on it?

**Comment by mlegenhausen** [comment]
Sorry for the waiting. Prevented any work during my vacations :wink:

Typings are merged I will create a new release.
