### ISSUE TITLE
responseError not raised when my http get 401 UnAuthorized error

### ISSUE THREAD

**Issue by wyshmily** [werk85/fetch-intercept#16]
Why?

**Comment by mlegenhausen** [comment]
This is cause the native fetch library makes no assumptions about the response code if it is an error or a wanted behaviour. You can convert your response to an error and handle it afterwards. Example

```js
fetchIntercept.register({
  response: function (response) {
    if (response.code >= 400) throw new Error('Request error');
      return response;
  }
});

fetchIntercept.register({
  responseError: function (error) {
    // Handle your error thrown from the previous interceptor here
  }
});
```

**Comment by wyshmily** [comment]
Thanks

**Comment by VasiliyPolyakov** [comment]
@mlegenhausen Hello! Can you help me? I have the same issue. I did everything that you wrote, but unfortunately, I could not handle the error in responseError

**Comment by VasiliyPolyakov** [comment]
Hello. Thank you for the answer. I did everything like you, but unfortunately, my component (showNotification) was not called in responseError for some reasons. I can't understand why. Maybe I am doing something wrong

my code: 
fetchIntercept.register({
  response: function(response) {
    if (response.status >= 401) throw new Error('Request error');
    return response;
  }
});

fetchIntercept.register({
  responseError: function(error) {
    console.log('error', error)
    showNotification(error);
  }
});

**Comment by mlegenhausen** [comment]
Try out to regsiter the `responseError` before the `response` listener. Internally I reverse the order of the interceptors to conform with the angular behavior.

**Comment by VasiliyPolyakov** [comment]
@mlegenhausen  awesome!!! It works. Thank you very much for quick answer.
