### ISSUE TITLE
Possible to use this lib w/ isomorphic-fetch instead of whatwg-fetch?

### ISSUE THREAD

**Issue by Miikis** [werk85/fetch-intercept#54]
Hi. It doesn't look like it's possible to swap out the `fetch` implementation currently. Is it? If not, will it be? As it stands, we're using isomorphic-fetch throughout our codebase and the interceptors from this lib aren't picking up the network traffic.

**Comment by mlegenhausen** [comment]
You need to make sure that `isomorphic-fetch` is added to the `global.fetch` object before `fetch-intercept` is called. Take a look here for debugging purposes: https://github.com/werk85/fetch-intercept/blob/develop/src/attach.js#L33-L40

**Comment by Miikis** [comment]
We decided to go another way but thanks for the reply. I'm gonna close this now.

**Comment by Phalguna2125** [comment]
Hi @Miikis @mlegenhausen  , we are using isomorphic fetch through out code base of nextjs server and client end. Any possible suggestion on how to intercept the requests? 
@Miikis Did you find any work around for this? 
Thanks in advance.
